export interface UpdateAiAgentConfigRequest {
    name?: string,
    model?: string,
    visionModel?: string,
    recordingModel?: string,
    provider?: string
    title?: string,
    inputPlaceholder?: string,
    systemMessage?: string,
    testMode?: boolean,
    accessPassword?: string,
    accessPasswordEnabled?: boolean,
    exemplaryPrompts?: string[],
    temperature?: number | null,
    topP?: number | null,
    maxTokens?: number | null,
    presencePenalty?: number | null,
    frequencyPenalty?: number | null,
    shortTermMemoryLastMessages?: number | null,
    fileUploadEnabled?: boolean,
    recordingEnabled?: boolean,
    chatUi?: "DEFAULT" | "CHATKIT",
    chatkitWorkflowId?: string,
}
