# syntax=docker/dockerfile:1.10

FROM amazoncorretto:25-alpine3.24 AS dev
WORKDIR /workspace
RUN apk add --no-cache bash su-exec
RUN mkdir -p /workspace/storage/documents
RUN mkdir -p /root/.gradle && \
    printf "org.gradle.daemon=true\n" >> /root/.gradle/gradle.properties

CMD ["sh", "./scripts/dev-backend-watch.sh"]

FROM amazoncorretto:25-alpine3.24 AS build
WORKDIR /app
COPY . .
RUN chmod +x ./gradlew
RUN --mount=type=cache,target=/root/.gradle,sharing=locked ./gradlew bootJar -x test --no-daemon --build-cache --parallel

FROM amazoncorretto:25-alpine3.24 AS runner
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
